version: 1
disable_existing_loggers: True
formatters:
  # Add new formatters if needed by your application
  basic:
    format: '%(asctime)s: %(name)-36s %(levelname)-8s %(message)s'
handlers:
  # Console and file loggers have their own configuration
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: basic
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: basic
    # FIXME: log file should go to output.
    filename: slayer.log
    mode: w
    encoding: utf-8
root:
  level: INFO
  propagate: True
  handlers: [console, file]