version: 1
disable_existing_loggers: True
formatters:
  # Add new formatters if needed by your application
  basic:
    format: '%(asctime)s: %(name)-6s %(levelname)-8s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: basic
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: basic
    # FIXME: log file should go to output.
    filename: slayer.log
    mode: w
    encoding: utf-8
root:
  level: DEBUG
  propagate: True
  handlers: [console, file]
